const EXT_LANG: Record<string, string> = {
  ts: "TypeScript",
  tsx: "TypeScript",
  js: "JavaScript",
  jsx: "JavaScript",
  mjs: "JavaScript",
  cjs: "JavaScript",
  py: "Python",
  go: "Go",
  rs: "Rust",
  java: "Java",
  kt: "Kotlin",
  rb: "Ruby",
  php: "PHP",
  cs: "C#",
  cpp: "C++",
  c: "C",
  h: "C",
  swift: "Swift",
  vue: "Vue",
  svelte: "Svelte",
  scala: "Scala",
  json: "JSON",
  md: "Markdown",
  yml: "YAML",
  yaml: "YAML",
  toml: "TOML",
  css: "CSS",
  scss: "SCSS",
  html: "HTML",
  // Additional languages
  sh: "Shell",
  bash: "Bash",
  zsh: "Zsh",
  lua: "Lua",
  perl: "Perl",
  pl: "Perl",
  dart: "Dart",
  elixir: "Elixir",
  exs: "Elixir",
  ex: "Elixir",
  erlang: "Erlang",
  hrl: "Erlang",
  haskell: "Haskell",
  hs: "Haskell",
  clojure: "Clojure",
  clj: "Clojure",
  cljs: "ClojureScript",
  fsharp: "F#",
  fs: "F#",
  objectivec: "Objective-C",
  mm: "Objective-C",
  matlab: "MATLAB",
  m: "MATLAB",
  r: "R",
  julia: "Julia",
  jl: "Julia",
  solidity: "Solidity",
  sol: "Solidity",
  sql: "SQL",
  graphql: "GraphQL",
  gql: "GraphQL",
  proto: "Protocol Buffers",
  dockerfile: "Dockerfile",
  makefile: "Makefile",
  cmake: "CMake",
};

export const SOURCE_EXTS = new Set([
  "ts",
  "tsx",
  "js",
  "jsx",
  "mjs",
  "cjs",
  "py",
  "go",
  "rs",
  "java",
  "kt",
  "rb",
  "php",
  "cs",
  "cpp",
  "c",
  "swift",
  "vue",
  "svelte",
  "scala",
  // Additional source file extensions
  "sh",
  "bash",
  "zsh",
  "lua",
  "pl",
  "perl",
  "dart",
  "exs",
  "ex",
  "erlang",
  "hrl",
  "hs",
  "haskell",
  "clj",
  "cljs",
  "clojure",
  "fs",
  "fsharp",
  "mm",
  "objectivec",
  "m",
  "matlab",
  "r",
  "jl",
  "julia",
  "sol",
  "solidity",
  "sql",
  "gql",
  "graphql",
  "proto",
]);

export const CONFIG_FILES = new Set([
  "package.json",
  "tsconfig.json",
  "cargo.toml",
  "pyproject.toml",
  "requirements.txt",
  "go.mod",
  "pom.xml",
  "build.gradle",
  "vite.config.ts",
  "vite.config.js",
  "next.config.js",
  "next.config.ts",
  "webpack.config.js",
  ".eslintrc.json",
  "tailwind.config.js",
  "tailwind.config.ts",
]);

export function detectLanguage(path: string): string | undefined {
  const ext = path.split(".").pop()?.toLowerCase();
  return ext ? EXT_LANG[ext] : undefined;
}

export function isSourceFile(path: string): boolean {
  const ext = path.split(".").pop()?.toLowerCase();
  return !!ext && SOURCE_EXTS.has(ext);
}

export function isConfigFile(path: string): boolean {
  const name = path.split("/").pop()?.toLowerCase() ?? "";
  return CONFIG_FILES.has(name);
}
